services:
  server:
    build:
      context: ./server
    environment:
      - RAY_DASHBOARD_HOST=0.0.0.0
      - RAY_METRICS_EXPORT_PORT=8080
    ports:
      - "8000:8000"
      - "8265:8265"
      - "8080:8080"
    develop:
      watch:
        - action: sync+restart
          path: ./server
          target: /app
    shm_size: "2gb"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./server/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - server

  client:
    build:
      context: ./client
    depends_on:
      - server
    environment:
      - FLASK_DEBUG=1
      - IMAGE_DIR=/app/images
      - SERVER_HOST=server
      - SERVER_PORT=8000
    ports:
      - "5001:5001"
    develop:
      watch:
        - action: sync+restart
          path: ./client
          target: /app
