services:
  server:
    build:
      context: ./server
    ports:
      - "8001:8001"
    develop:
      watch:
        - action: sync+restart
          path: ./server
          target: /app

  client:
    build:
      context: ./client
    depends_on:
      - server
    environment:
      - FLASK_DEBUG=1
      - IMAGE_DIR=/app/images
      - MODEL_SERVER_HOST=server
      - MODEL_SERVER_PORT=8001
    ports:
      - "5001:5001"
    develop:
      watch:
        - action: sync+restart
          path: ./client
          target: /app
