apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: ml-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: client-image:latest
          imagePullPolicy: Never
          command: ["python", "client.py"]
          ports:
            - containerPort: 8000
              name: metrics
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          env:
            - name: SERVER_HOST
              value: "dispatcher-service.ml-apps.svc.cluster.local"
            - name: SERVER_PORT
              value: "8000"
