apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: ml-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: worker-image:latest
          imagePullPolicy: Never
          command: ["python", "worker.py"]
          resources:
            limits:
              cpu: "1000m"
              memory: "1024Mi"
            requests:
              cpu: "1000m"
              memory: "1024Mi"
          env:
            - name: DISPATCHER_URL
              value: "http://dispatcher-service.ml-apps.svc.cluster.local:8000"
