apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-sa
  namespace: ml-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: autoscaler-role
  namespace: ml-apps
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autoscaler-rb
  namespace: ml-apps
subjects:
  - kind: ServiceAccount
    name: autoscaler-sa
    namespace: ml-apps
roleRef:
  kind: Role
  name: autoscaler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-autoscaler
  namespace: ml-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      serviceAccountName: autoscaler-sa
      containers:
        - name: autoscaler
          image: autoscaler-image:latest
          imagePullPolicy: Never
          command: ["python", "autoscaler.py"]
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: NAMESPACE
              value: ml-apps
            - name: PROM_URL
              value: http://prometheus-service.monitoring.svc.cluster.local:9090/api/v1/query
            - name: DEPLOYMENT_NAME
              value: worker-deployment
            - name: MIN_REPLICAS
              value: "1"
            - name: MAX_REPLICAS
              value: "3"
            - name: SCALE_DOWN_COOLDOWN
              value: "5"
