apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: client-image:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "250m"
              memory: "250Mi"
            requests:
              cpu: "250m"
              memory: "250Mi"
          env:
            - name: SERVER_HOST
              value: "server"
            - name: SERVER_PORT
              value: "8000"
