apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: "ray-metrics"
        static_configs:
          - targets: ["server:8080"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: "500m" # The absolute maximum CPU ceiling for the container.
              memory: "512Mi" # The absolute maximum RAM allocation ceiling.
            requests:
              cpu: "250m" # The minimum CPU capacity required on initialization.
              memory: "256Mi" # The minimum RAM capacity required on initialization.
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: dashboard
      protocol: TCP
      port: 9090
      targetPort: 9090
